version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rcb-pfp-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/saved_models:/app/saved_models
      - ./bg:/app/bg
    environment:
      - DEBUG=False
      - PORT=5000
      - UPLOAD_FOLDER=uploads
      - BG_FOLDER=bg
      - MODEL_DIR=saved_models
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: rcb-pfp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    restart: unless-stopped 