services:
  # Backend API service
  - type: web
    name: rcb-pfp-generator-backend
    env: python
    plan: free  # Free tier
    buildCommand: cd backend && pip install -r requirements.txt && python download_model.py
    startCommand: cd backend && gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: false
      - key: UPLOAD_FOLDER
        value: uploads
      - key: BG_FOLDER
        value: bg
      - key: MODEL_DIR
        value: saved_models
    # Removed disk configuration as it's not supported in free tier

  # Frontend static site (using web type with static publishing)
  - type: web
    name: rcb-pfp-generator-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: rcb-pfp-generator-backend$path
    envVars:
      - key: REACT_APP_API_URL
        value: ""  # Empty value to use relative URLs 